// src/tabs/output.ts
import { getLastOutput } from '../state';

export async function mount(tabContent: HTMLElement): Promise<void> {
  // ensure a root for output
  let root = document.getElementById('output-root') as HTMLDivElement | null;
  if (!root) {
    root = document.createElement('div');
    root.id = 'output-root';
    tabContent.innerHTML = '';
    tabContent.appendChild(root);
  } else {
    root.innerHTML = '';
  }

  const last = getLastOutput();
  if (!last) {
    root.innerHTML = `<div style="color:var(--muted)">No design rendered yet. Generate from Design tab.</div>`;
    return;
  }

  // render last saved HTML safely (it's generated by our service)
  root.innerHTML = last;
}
